/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package covidgui;

import classes.Patient;
import classes.VaccinationData;
import classes.database;
import java.time.DateTimeException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author husse
 */
public class NewPatient extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public NewPatient() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RDGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        save1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RDF = new javax.swing.JRadioButton();
        CBM = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TFn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        have = new javax.swing.JRadioButton();
        RDM = new javax.swing.JRadioButton();
        CBD = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TFY = new javax.swing.JTextField();
        TFid = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        vcb = new javax.swing.JComboBox<>();
        save2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nodcb = new javax.swing.JComboBox<>();
        d1month = new javax.swing.JComboBox<>();
        d1day = new javax.swing.JComboBox<>();
        d1year = new javax.swing.JTextField();
        d2day = new javax.swing.JComboBox<>();
        d2year = new javax.swing.JTextField();
        d2month = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        LBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(910, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 510));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        jLabel3.setText("New Patient");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 50));

        save1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        save1.setText("Save");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel2.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 90, 30));

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel4.setText("ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        RDGroup.add(RDF);
        RDF.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        RDF.setText("Female");
        RDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDFActionPerformed(evt);
            }
        });
        jPanel2.add(RDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        CBM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "Decembe", " " }));
        CBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMActionPerformed(evt);
            }
        });
        jPanel2.add(CBM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 80, 30));

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel7.setText("Gender");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        TFn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnActionPerformed(evt);
            }
        });
        jPanel2.add(TFn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, 30));

        jLabel9.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel9.setText("Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 30));

        have.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        have.setText("Have vaccine");
        have.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haveActionPerformed(evt);
            }
        });
        jPanel2.add(have, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 30));

        RDGroup.add(RDM);
        RDM.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        RDM.setText("Male");
        RDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDMActionPerformed(evt);
            }
        });
        jPanel2.add(RDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        CBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        jPanel2.add(CBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 50, 30));

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel8.setText("Date of birth");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));
        jPanel2.add(TFY, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 60, 30));
        jPanel2.add(TFid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 210, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel10.setText("Vaccine ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        vcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pfizer", "AstraZeneca", "Janssen", "Moderna", "Sinopharm" }));
        vcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcbActionPerformed(evt);
            }
        });
        jPanel1.add(vcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 180, 30));

        save2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        save2.setText("Save");
        save2.setEnabled(false);
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });
        jPanel1.add(save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 290, 80, 30));

        jLabel11.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel11.setText("Date of second date:");
        jLabel11.setEnabled(false);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jLabel12.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel12.setText("Date of first date:");
        jLabel12.setEnabled(false);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        jLabel13.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel13.setText("Number of doses:");
        jLabel13.setEnabled(false);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        nodcb.setEnabled(false);
        nodcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodcbActionPerformed(evt);
            }
        });
        jPanel1.add(nodcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, 30));

        d1month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "Decembe" }));
        d1month.setEnabled(false);
        jPanel1.add(d1month, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 80, 30));

        d1day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        d1day.setEnabled(false);
        jPanel1.add(d1day, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 50, 30));

        d1year.setEnabled(false);
        jPanel1.add(d1year, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 60, 30));

        d2day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        d2day.setEnabled(false);
        jPanel1.add(d2day, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 50, 30));

        d2year.setEnabled(false);
        jPanel1.add(d2year, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 60, 30));

        d2month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "Decembe" }));
        d2month.setEnabled(false);
        jPanel1.add(d2month, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 80, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/lightBlue.jpg"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 340));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 460, 340));

        LBL.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LBL.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(LBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 320, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/lightBlue.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 901, 490));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 901, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        try {
            if (TFid.getText().equals("") || TFn.getText().equals("") || RDGroup.getSelection() == null || TFY.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Fill all informations please");
            } else {
                String name = TFn.getText();
                String id = TFid.getText();
                String gender = "";
                if (RDM.isSelected()) {
                    gender = "Male";
                } else if (RDF.isSelected()) {
                    gender = "Female";

                }
                int d = Integer.parseInt(CBD.getSelectedItem().toString());
                int m = CBM.getSelectedIndex() + 1;
                int y = Integer.parseInt(TFY.getText());
                LocalDate date = LocalDate.of(y, m, d);

                new Patient(name, date, id, gender, null, 'N');

                clearNewP();
                JOptionPane.showMessageDialog(rootPane, "Added successfully");
            }
        } catch (DateTimeException dte) {
            JOptionPane.showMessageDialog(rootPane, "Incorrect Date");
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Please enter correct year");
        }
    }//GEN-LAST:event_save1ActionPerformed

    private void RDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDFActionPerformed

    private void RDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDMActionPerformed

    private void CBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBMActionPerformed

    private void haveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haveActionPerformed
        if (have.isSelected()) {
            jPanel1.setVisible(true);
            save1.setEnabled(false);
        } else {
            jPanel1.setVisible(false);
            save1.setEnabled(true);
        }
    }//GEN-LAST:event_haveActionPerformed

    private void vcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcbActionPerformed
        nodcb.setEnabled(true);
        jLabel13.setEnabled(true);
        jLabel12.setEnabled(true);
        d1day.setEnabled(true);
        d1month.setEnabled(true);
        d1year.setEnabled(true);
        save2.setEnabled(true);
        if (vcb.getSelectedIndex() == 2) {
            nodcb.addItem("1");
            jLabel12.setEnabled(true);
        } else {
            nodcb.addItem("1");
            nodcb.addItem("2");
        }
    }//GEN-LAST:event_vcbActionPerformed

    private void nodcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodcbActionPerformed
        if (nodcb.getSelectedIndex() == 1) {
            d2day.setEnabled(true);
            d2month.setEnabled(true);
            d2year.setEnabled(true);
            jLabel11.setEnabled(true);
        }
    }//GEN-LAST:event_nodcbActionPerformed

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed
        try {
            LocalDate vd1;
            LocalDate vd2;
            if (nodcb.getSelectedIndex() == 0) {
                vd1 = LocalDate.of(Integer.parseInt(d1year.getText()), d1month.getSelectedIndex() + 1, d1day.getSelectedIndex() + 1);
                vd2 = null;
            } else {
                vd1 = LocalDate.of(Integer.parseInt(d1year.getText()), d1month.getSelectedIndex() + 1, d1day.getSelectedIndex() + 1);
                vd2 = LocalDate.of(Integer.parseInt(d2year.getText()), d2month.getSelectedIndex() + 1, d2day.getSelectedIndex() + 1);
            }

            VaccinationData vd = new VaccinationData(database.getVaccineByName(vcb.getSelectedItem().toString()), vd1, vd2, nodcb.getSelectedIndex() + 1);

            if (TFid.getText().equals("") || TFn.getText().equals("") || RDGroup.getSelection() == null || TFY.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Fill all informations please");
            } else {
                String name = TFn.getText();
                String id = TFid.getText();
                String gender = "";
                if (RDM.isSelected()) {
                    gender = "Male";
                } else if (RDF.isSelected()) {
                    gender = "Female";

                }//we can use another else if he didnt press on any gender then we show on LBL that he has to pick one
                int d = Integer.parseInt(CBD.getSelectedItem().toString());
                int m = CBM.getSelectedIndex() + 1;
                
                int y = Integer.parseInt(TFY.getText());
                LocalDate date = LocalDate.of(y, m, d);

                new Patient(name, date, id, gender, vd, 'N');
                
                clearNewP();
                vcb.setSelectedIndex(0);
                nodcb.setSelectedIndex(0);
                d1day.setSelectedIndex(0);
                d1month.setSelectedIndex(0);
                d1year.setText("");
                d2day.setSelectedIndex(0);
                d2month.setSelectedIndex(0);
                d2year.setText("");
                jPanel1.setVisible(false);
                JOptionPane.showMessageDialog(rootPane, "Added successfully");
            }
        } catch (DateTimeException dte) {
            JOptionPane.showMessageDialog(rootPane, "Incorrect Date");
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Please enter correct year");
        }
    }//GEN-LAST:event_save2ActionPerformed

    private void clearNewP(){
        TFn.setText("");
        RDGroup.clearSelection();
        CBM.setSelectedIndex(0);
        CBD.setSelectedIndex(0);
        TFY.setText("");
        TFid.setText("");
        have.setSelected(false);
    }
    
    private void initialize() {
        jPanel1.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBD;
    private javax.swing.JComboBox<String> CBM;
    private javax.swing.JLabel LBL;
    private javax.swing.JRadioButton RDF;
    private javax.swing.ButtonGroup RDGroup;
    private javax.swing.JRadioButton RDM;
    private javax.swing.JTextField TFY;
    private javax.swing.JTextField TFid;
    private javax.swing.JTextField TFn;
    private javax.swing.JComboBox<String> d1day;
    private javax.swing.JComboBox<String> d1month;
    private javax.swing.JTextField d1year;
    private javax.swing.JComboBox<String> d2day;
    private javax.swing.JComboBox<String> d2month;
    private javax.swing.JTextField d2year;
    private javax.swing.JRadioButton have;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> nodcb;
    private javax.swing.JButton save1;
    private javax.swing.JButton save2;
    private javax.swing.JComboBox<String> vcb;
    // End of variables declaration//GEN-END:variables
}
