/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package covidgui;

import classes.Person;
import classes.database;
import java.time.DateTimeException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author husse
 */
public class newTest extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public newTest() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RDGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PANEL = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RDM = new javax.swing.JRadioButton();
        RDF = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        CBD = new javax.swing.JComboBox<>();
        CBM = new javax.swing.JComboBox<>();
        TFY = new javax.swing.JTextField();
        TFn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        LBL = new javax.swing.JLabel();
        RDE = new javax.swing.JRadioButton();
        RDN = new javax.swing.JRadioButton();
        TFid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(910, 520));

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 510));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        jLabel3.setText("New Test");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 50));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel2.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jButton2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton2.setText("AVAILABLE DATES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setText("ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        PANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel9.setText("Name");
        PANEL.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel7.setText("Gender");
        PANEL.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        RDGroup.add(RDM);
        RDM.setText("Male");
        RDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDMActionPerformed(evt);
            }
        });
        PANEL.add(RDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        RDGroup.add(RDF);
        RDF.setText("Female");
        RDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDFActionPerformed(evt);
            }
        });
        PANEL.add(RDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel8.setText("Date of birth");
        PANEL.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        CBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        PANEL.add(CBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        CBM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        PANEL.add(CBM, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));
        PANEL.add(TFY, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 110, -1));

        TFn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnActionPerformed(evt);
            }
        });
        PANEL.add(TFn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 210, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/lightBlue.jpg"))); // NOI18N
        PANEL.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 140));

        jPanel2.add(PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 450, 140));

        LBL.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LBL.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(LBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 320, 70));

        RDE.setText("Existing paitent");
        RDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDEActionPerformed(evt);
            }
        });
        jPanel2.add(RDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        RDN.setText("New Paitent ");
        RDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDNActionPerformed(evt);
            }
        });
        jPanel2.add(RDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));
        jPanel2.add(TFid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/lightBlue.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 901, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (TFid.getText().equals("") || TFn.getText().equals("") || RDGroup.getSelection() == null || TFY.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Fill all informations please");
            } else {
                if (RDN.isSelected()) {

                    String name = TFn.getText();
                    String id = TFid.getText();
                    String gender = "";
                    if (RDM.isSelected()) {
                        gender = "Male";
                    } else if (RDF.isSelected()) {
                        gender = "Female";

                    }//we can use another else if he didnt press on any gender then we show on LBL that he has to pick one
                    int d = Integer.parseInt(CBD.getSelectedItem().toString());
                    int m = Integer.parseInt(CBM.getSelectedItem().toString());
                    int y = Integer.parseInt(TFY.getText());
                    LocalDate date = LocalDate.of(y, m, d);

                    Person person = new Person(name, date, id, gender);
                    // i will add paitent constructor and add rdb to check if he has vaccine or not 
                    // if he has vaccine add vaccination data to the paitent 
                } else if (RDE.isSelected()) {
                    String id = TFid.getText();
                    if (database.getPatientById(id) != null) {

                    } else {
                        LBL.setText("Enter A valid ID");
                    }
                }
            }

            //maybe i should add date of birth into person class
        } catch (DateTimeException dte) {
            JOptionPane.showMessageDialog(rootPane, "Incorrect Date");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDFActionPerformed

    private void RDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDMActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cb1.removeAllItems();
        cb1.addItem(LocalDate.now().toString());
        cb1.addItem(LocalDate.now().plusDays(2).toString());
        cb1.addItem(LocalDate.now().plusDays(4).toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDEActionPerformed
        // TODO add your handling code here:
        PANEL.setVisible(false);
        RDN.setSelected(false);

    }//GEN-LAST:event_RDEActionPerformed

    private void RDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDNActionPerformed
        // TODO add your handling code here:
        RDE.setSelected(false);
        PANEL.setVisible(true);


    }//GEN-LAST:event_RDNActionPerformed

    private void initialize() {
        PANEL.setVisible(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBD;
    private javax.swing.JComboBox<String> CBM;
    private javax.swing.JLabel LBL;
    private javax.swing.JPanel PANEL;
    private javax.swing.JRadioButton RDE;
    private javax.swing.JRadioButton RDF;
    private javax.swing.ButtonGroup RDGroup;
    private javax.swing.JRadioButton RDM;
    private javax.swing.JRadioButton RDN;
    private javax.swing.JTextField TFY;
    private javax.swing.JTextField TFid;
    private javax.swing.JTextField TFn;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
